export const participantsFormData = {
  seniority: [
    {value: "Entry-level",label: "Entry-level"},
    {value:  "Manager",label:  "Manager"},
    {value:  "Senior Manager",label:  "Senior Manager"},
    {value:  "Deputy Manager",label:  "Deputy Manager"},
    {value: "Director",label: "Director"},
    {value: "Vice Preseident(VP)",label: "Vice Preseident(VP)"},
    {value: "Chief X Office(CXO)",label: "Chief X Office(CXO)"},
    {value: "C Level Executives",label: "C Level Executives"},
    {value: "Partner",label: "Partner"},
    {value: "Owner",label: "Owner"},
    {value: "Under Training",label: "Under Training"},
    {value: "Unpaid",label: "Unpaid"},
],
companysize: [
    {value: "Just me",label: "Just me"},
    {value: "2-10 employees",label: "2-10 employees"},
    {value: "11-50 employees",label: "11-50 employees"},
    {value: "51-200 employees",label: "51-200 employees"},
    {value:  "201-1000 employees",label:  "201-1000 employees"},
    {value: "1001-5000 employees",label: "1001-5000 employees"},
    {value: "5001-10,000 employees",label: "5001-10,000 employees"},
    {value: "10,000+ employees",label: "10,000+ employees"},
],
worksetting: [
    { value: "Remote", label: "Remote" },
    { value: "On-site", label: "On-site" },
    { value: "Hybrid", label: "Hybrid" },
  ],
  // smallbusinessowner: [
  //   { value: "Yes", label: "Yes" },
  //   { value: "No", label: "No" },
  // ],
  gender: [
    { value: "M", label: "Male" },
    { value: "F", label: "Female" },
  ],
  education: [
    { value: "Didn't finish high school", label: "Didn't finish high school" },
    { value: "Finished high school", label: "Finished high school" },
    { value: "Undergraduate degree", label: "Undergraduate degree" },
    { value: "Postgraduate degree", label: "Postgraduate degree" },
    { value: "PhD(Doctor of Philosophy)", label: "PhD(Doctor of Philosophy)" },
    { value: "Distance Education", label: "Distance Education" },
  ],
  maritalstatus: [
    { value: "Never married", label: "Never married" },
    { value: "Married", label: "Married" },
    { value: "Divorced or separated", label: "Divorced or Separated" },
    { value: "Widowed", label: "Widowed" },
  ],
  language: [
    { value: "Fluent", label: "Fluent" },
    { value: "Advanced", label: "Advanced" },
    { value: "Intermediate", label: "Intermediate" },
    { value: "Basic", label: "Basic" },
    { value: "None", label: "None" },
  ],
  homeowner: [
    { value: "Yes", label: "Yes" },
    { value: "No", label: "No" },
  ],
  carowner: [
    { value: "Yes", label: "Yes" },
    { value: "No", label: "No" },
  ],
  petparent: [  
    { value: "Yes", label: "Yes" },
    { value: "No", label: "No" },
  ],
  creditcard: [
    { value: "Yes", label: "Yes" },
    { value: "No", label: "No" },
  ],
  mobileos: [
    { value: "IOS", label: "IOS" },
    { value: "Android", label: "Android" },
    { value: "Symbian", label: "Symbian" },
    { value: "HMOS", label: "HMOS" },
    { value: "None", label: "None" },
  ],
  tabletos: [
    { value: "IOS", label: "IOS" },
    { value: "Android", label: "Android" },
    { value: "Chrome OS", label: "Chrome OS" },
    { value: "Windows", label: "Windows" },
    { value: "None", label: "None" },
  ],
  laptopos: [
    { value: "MAC OS", label: "MAC OS" },
    { value: "Windows OS", label: "Windows OS" },
    { value: "Linux OS", label: "Linux OS" },
    { value: "Android OS", label: "Android OS" },
    { value: "Chrome OS", label: "Chrome OS" },
    { value: "None", label: "None" },
  ],
};

export const researchersFormData = {
  professional: [
    {value: "Data Analyst",label: "Data Analyst"},
    {value:  "Customer Success",label:  "Customer Success"},
    {value: "Engineering",label: "Engineering"},
    {value: "Product management",label: "Product management"},
    {value: "UX Design / Research",label: "UX Design / Research"},
    {value: "Researcher",label: "Researcher"},
    {value: "Operator",label: "Operator"},
],
role: [
    {value: "Freelance / Self employed",label: "Freelance / Self employed"},
    {value: "Individual Contributor",label: "Individual Contributor"},
    {value: "Product Manager / SPM",label: "Product Manager / SPM"},
    {value: "User Researcher / Senior",label: "User Researcher / Senior"},
    {value: "Director / Sr Director",label: "Director / Sr Director"},
    {value:  "Head of Product / CPO",label:  "Head of Product / CPO"},
    {value: "VP / Sr VP",label: "VP / Sr VP"},
    {value: "C Level Founder / Operator",label: "C Level Founder / Operator"},
    {value: "Others / Not Listed",label: "Others / Not Listed"},
],
audiencetype: [
    { value: "Consumers / Users", label: "Consumers / Users" },
    { value: "Professionals", label: "Professionals" },
  ],
  modeofconnect: [
    { value: "Online", label: "Online" },
    { value: "Inperson", label: "Inperson" },
  ],
};
